"""Planning primitives for conflict-aware multi-world SQL witnesses."""

from .obligations import (
    ConstraintSpec,
    DistinguishingObligation,
    compile_obligations,
    is_redundant_summary_diff,
    stable_diff_id,
)
from .schema_scope import (
    ColumnRef,
    ColumnSchema,
    ForeignKey,
    QueryScope,
    SchemaCatalog,
    SchemaQualification,
    TableSchema,
    analyze_schema_qualification,
    extract_physical_table_names,
)
from .planner import (
    CellConstraint,
    ConstraintConflict,
    ConstraintLedger,
    StrategyDeclaration,
    WitnessPlanner,
    WitnessSuite,
    WitnessWorld,
    apply_bounded_feedback,
    apply_cell_constraints,
    declare_strategy,
    split_world_on_conflict,
)
from .adapters import (
    AdapterRun,
    LegacyProbeAdapter,
    LegacyProbeRegistry,
    adapter_owner,
    run_adapter,
)
from .validators import ObligationValidation, validate_obligation

__all__ = [
    "ColumnRef",
    "ColumnSchema",
    "ForeignKey",
    "AdapterRun",
    "CellConstraint",
    "ConstraintConflict",
    "ConstraintLedger",
    "ConstraintSpec",
    "DistinguishingObligation",
    "QueryScope",
    "SchemaCatalog",
    "SchemaQualification",
    "StrategyDeclaration",
    "WitnessPlanner",
    "WitnessSuite",
    "WitnessWorld",
    "TableSchema",
    "LegacyProbeAdapter",
    "LegacyProbeRegistry",
    "adapter_owner",
    "analyze_schema_qualification",
    "apply_bounded_feedback",
    "apply_cell_constraints",
    "compile_obligations",
    "is_redundant_summary_diff",
    "declare_strategy",
    "split_world_on_conflict",
    "extract_physical_table_names",
    "stable_diff_id",
    "run_adapter",
    "ObligationValidation",
    "validate_obligation",
]
