"""Bound and sanitize learner-visible schema previews.

Schema previews may be authored by a teacher or generated by an LLM that has
seen the reference SQL.  They therefore cross the same trust boundary as a
diagnostic package: only a small structural allow-list may reach learners.
"""

from __future__ import annotations

from decimal import Decimal, InvalidOperation
import json
import math
import re
from typing import Any, Mapping, Sequence


MAX_INPUT_BYTES = 256 * 1024
MAX_OUTPUT_BYTES = 128 * 1024
MAX_TABLES = 16
MAX_COLUMNS = 64
MAX_ROWS_PER_TABLE = 8
MAX_CELL_STRING = 240

_SQL_SHAPED_TEXT = re.compile(
    r"\b(?:select\b[\s\S]{0,500}\bfrom\b|insert\s+into\b|"
    r"update\b[\s\S]{0,200}\bset\b|delete\s+from\b|"
    r"drop\s+(?:table|database)\b|with\b[\s\S]{0,500}\bselect\b)",
    flags=re.IGNORECASE,
)
_IDENTIFIER_COMPONENT = r"(?:[^\W\d][\w$]*|_[\w$]*)"
_IDENTIFIER = re.compile(rf"^{_IDENTIFIER_COMPONENT}$", flags=re.UNICODE)
_QUALIFIED_IDENTIFIER = re.compile(
    rf"^{_IDENTIFIER_COMPONENT}(?:\.{_IDENTIFIER_COMPONENT})*$",
    flags=re.UNICODE,
)
_TYPE_DECLARATION = re.compile(
    r"^([A-Za-z]+(?:\s+[A-Za-z]+){0,3})"
    r"(?:\(\d{1,5}(?:\s*,\s*\d{1,5})?\))?"
    r"(?:\s+UNSIGNED)?$",
    flags=re.IGNORECASE,
)
_ALLOWED_TYPE_NAMES = {
    "BIGINT",
    "BINARY",
    "BLOB",
    "BOOL",
    "BOOLEAN",
    "CHAR",
    "CHARACTER",
    "CHARACTER VARYING",
    "CLOB",
    "DATE",
    "DATETIME",
    "DECIMAL",
    "DOUBLE",
    "DOUBLE PRECISION",
    "FLOAT",
    "INT",
    "INTEGER",
    "JSON",
    "NCHAR",
    "NTEXT",
    "NUMBER",
    "NUMERIC",
    "NVARCHAR",
    "REAL",
    "SMALLINT",
    "TEXT",
    "TIME",
    "TIMESTAMP",
    "TIMESTAMP WITH TIME ZONE",
    "TIMESTAMP WITHOUT TIME ZONE",
    "TINYINT",
    "UUID",
    "VARBINARY",
    "VARCHAR",
}
_REFERENCE_CLAUSE = re.compile(
    r"\b(?:WHERE|HAVING|QUALIFY|ON|GROUP\s+BY|ORDER\s+BY|LIMIT|OFFSET)\b"
    r"\s+(.+?)(?=\b(?:WHERE|HAVING|QUALIFY|JOIN|GROUP\s+BY|ORDER\s+BY|"
    r"LIMIT|OFFSET|UNION|INTERSECT|EXCEPT)\b|$)",
    flags=re.IGNORECASE | re.DOTALL,
)
_REFERENCE_COMPARISON = re.compile(
    r"\b[A-Za-z_][A-Za-z0-9_.]*\s*(?:<>|!=|<=|>=|=|<|>)\s*"
    r"(?:[-+]?\d+(?:\.\d+)?|'[^']{0,120}'|\"[^\"]{0,120}\"|"
    r"[A-Za-z_][A-Za-z0-9_.]*)",
    flags=re.IGNORECASE,
)
_REFERENCE_NUMBER = re.compile(
    r"(?<![\w.])[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?![\w.])"
)


def _sequence(value: Any) -> Sequence[Any]:
    return value if isinstance(value, (list, tuple)) else ()


def _normalized(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().rstrip(";")).lower()


def _reference_fragments(sql: str) -> tuple[str, ...]:
    normalized_sql = _normalized(sql)
    if len(normalized_sql) < 8:
        return ()
    fragments = {normalized_sql}
    for match in _REFERENCE_CLAUSE.finditer(sql):
        body = _normalized(match.group(1))
        if len(body) >= 4:
            fragments.add(body)
    for match in _REFERENCE_COMPARISON.finditer(sql):
        comparison = _normalized(match.group(0))
        if len(comparison) >= 4:
            fragments.add(comparison)
    return tuple(sorted(fragments, key=lambda item: (-len(item), item)))


def _reference_numbers(sql: str) -> frozenset[Decimal]:
    values: set[Decimal] = set()
    for match in _REFERENCE_NUMBER.finditer(sql):
        try:
            values.add(Decimal(match.group(0)).normalize())
        except InvalidOperation:
            continue
    return frozenset(values)


def _safe_text(
    value: Any,
    *,
    limit: int,
    secrets: Sequence[str],
) -> str | None:
    if not isinstance(value, str):
        return None
    text = value[: limit + 1].strip()[:limit]
    if not text:
        return None
    normalized = _normalized(text)
    if any(secret in normalized for secret in secrets) or _SQL_SHAPED_TEXT.search(text):
        return None
    return text


def _safe_identifier(
    value: Any,
    *,
    secrets: Sequence[str],
    qualified: bool = False,
) -> str | None:
    # Table/column names are structural inputs, not answer values.  They must
    # remain visible when a real question references them (for example
    # ``GROUP BY facid``); treating a referenced identifier as a secret makes
    # the API persist an incomplete catalog and turns a valid question into an
    # INPUT_GAP.  SQL-shaped identifier smuggling is still rejected below.
    text = _safe_text(value, limit=128, secrets=())
    pattern = _QUALIFIED_IDENTIFIER if qualified else _IDENTIFIER
    if not text or not pattern.fullmatch(text):
        return None
    # Identifiers are the only learner-visible free-text channel in this
    # payload.  Reject an answer query smuggled through identifier-safe
    # separators, for example ``SELECT_secret_FROM_private_table``.  Ordinary
    # names such as ``order_items`` remain valid because they do not form a
    # complete SQL-shaped fragment.
    decoded = re.sub(r"[_.$]+", " ", text)
    return None if _SQL_SHAPED_TEXT.search(decoded) else text


def _safe_cell(
    value: Any,
    *,
    secrets: Sequence[str],
    secret_numbers: frozenset[Decimal],
) -> Any:
    if value is None or isinstance(value, bool):
        return value
    if isinstance(value, int):
        return "[number]" if Decimal(value) in secret_numbers else value
    if isinstance(value, float):
        if not math.isfinite(value):
            return None
        try:
            numeric = Decimal(str(value)).normalize()
        except InvalidOperation:
            return None
        return "[number]" if numeric in secret_numbers else value
    if isinstance(value, str):
        # This channel may have been generated by a model that saw the
        # reference SQL.  No finite deny-list can distinguish an innocent
        # example label from a natural-language or expression-level repair
        # hint (for example ``COUNT(DISTINCT s_id)``).  Preserve only the fact
        # that the cell is textual; physical teaching witnesses come from the
        # independent Phase 1 sandbox instead.
        return "[text]"
    return "[unsupported]"


def _safe_type(value: Any, *, secrets: Sequence[str]) -> str | None:
    # Type declarations are structural metadata as well.  Keep the same
    # allow-list and SQL-shape checks, but do not remove a type merely because
    # a short token happens to occur in the answer text.
    text = _safe_text(value, limit=80, secrets=())
    if not text:
        return None
    match = _TYPE_DECLARATION.fullmatch(text)
    if not match:
        return None
    type_name = re.sub(r"\s+", " ", match.group(1)).upper()
    return text if type_name in _ALLOWED_TYPE_NAMES else None


def _column(column_raw: Any, *, secrets: Sequence[str]) -> dict[str, Any] | None:
    if isinstance(column_raw, str):
        name = _safe_identifier(column_raw, secrets=secrets)
        return {"name": name} if name else None
    if not isinstance(column_raw, Mapping):
        return None
    name = _safe_identifier(column_raw.get("name"), secrets=secrets)
    if not name:
        return None
    result: dict[str, Any] = {"name": name}
    type_value = column_raw.get("data_type", column_raw.get("type"))
    safe_type = _safe_type(type_value, secrets=secrets)
    if safe_type:
        result["data_type"] = safe_type
    for source, target in (
        ("nullable", "nullable"),
        ("primary_key", "primary_key"),
        ("is_primary_key", "primary_key"),
        ("unique", "unique"),
    ):
        if isinstance(column_raw.get(source), bool):
            result[target] = column_raw[source]
    return result


def _identifier_list(
    value: Any,
    *,
    allowed: Mapping[str, str] | None,
    secrets: Sequence[str],
) -> list[str]:
    result: list[str] = []
    seen: set[str] = set()
    raw_values = _sequence(value)
    # Constraint members are atomic.  Truncating or skipping one member can
    # turn a composite key into a false unary key, which is worse than
    # omitting the untrusted constraint entirely.
    if not raw_values or len(raw_values) > MAX_COLUMNS:
        return []
    for raw in raw_values:
        item = _safe_identifier(raw, secrets=secrets)
        if not item:
            return []
        normalized = item.casefold()
        if allowed is not None:
            item = allowed.get(normalized) or ""
            if not item:
                return []
            normalized = item.casefold()
        if normalized in seen:
            return []
        result.append(item)
        seen.add(normalized)
    return result


def _foreign_keys(
    value: Any,
    *,
    allowed: Mapping[str, str],
    secrets: Sequence[str],
) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    for raw in _sequence(value)[:MAX_COLUMNS]:
        if not isinstance(raw, Mapping):
            continue
        columns = _identifier_list(
            raw.get("columns") or ([raw.get("column")] if raw.get("column") else []),
            allowed=allowed,
            secrets=secrets,
        )
        reference_table = _safe_identifier(
            raw.get("references_table") or raw.get("reference_table"),
            secrets=secrets,
            qualified=True,
        )
        reference_columns = _identifier_list(
            raw.get("references_columns")
            or ([raw.get("references_column")] if raw.get("references_column") else []),
            allowed=None,
            secrets=secrets,
        )
        if (
            columns
            and reference_table
            and reference_columns
            and len(columns) == len(reference_columns)
        ):
            result.append(
                {
                    "columns": columns,
                    "references_table": reference_table,
                    "references_columns": reference_columns,
                }
            )
    return result


def sanitize_schema_preview_object(
    value: Any,
    *,
    forbidden_sql: str = "",
) -> dict[str, Any] | None:
    """Return the bounded structural allow-list, or ``None`` if unusable."""

    if isinstance(value, str):
        if len(value) > MAX_INPUT_BYTES or len(
            value.encode("utf-8", errors="ignore")
        ) > MAX_INPUT_BYTES:
            return None
        try:
            value = json.loads(value)
        except (TypeError, ValueError, json.JSONDecodeError):
            return None
    if not isinstance(value, Mapping):
        return None

    if not isinstance(forbidden_sql, str):
        return None
    if len(forbidden_sql) > MAX_INPUT_BYTES or len(
        forbidden_sql.encode("utf-8", errors="ignore")
    ) > MAX_INPUT_BYTES:
        return None
    secrets = _reference_fragments(forbidden_sql)
    secret_numbers = _reference_numbers(forbidden_sql)
    tables: list[dict[str, Any]] = []
    seen_table_names: set[str] = set()
    for table_raw in _sequence(value.get("tables"))[:MAX_TABLES]:
        if not isinstance(table_raw, Mapping):
            continue
        name = _safe_identifier(
            table_raw.get("name"),
            secrets=secrets,
            qualified=True,
        )
        if not name:
            continue
        normalized_name = name.casefold()
        if normalized_name in seen_table_names:
            continue
        seen_table_names.add(normalized_name)
        columns: list[dict[str, Any]] = []
        column_lookup: dict[str, str] = {}
        for column_raw in _sequence(table_raw.get("columns"))[:MAX_COLUMNS]:
            item = _column(column_raw, secrets=secrets)
            normalized_column = item["name"].casefold() if item else ""
            if item and normalized_column not in column_lookup:
                columns.append(item)
                column_lookup[normalized_column] = item["name"]

        table: dict[str, Any] = {"name": name, "columns": columns}
        primary_key = _identifier_list(
            table_raw.get("primary_key"), allowed=column_lookup, secrets=secrets
        )
        if primary_key:
            table["primary_key"] = primary_key
        unique_constraints: list[list[str]] = []
        seen_unique_constraints: set[tuple[str, ...]] = set()
        for raw_constraint in _sequence(
            table_raw.get("unique_constraints")
        )[:MAX_COLUMNS]:
            constraint = _identifier_list(
                raw_constraint,
                allowed=column_lookup,
                secrets=secrets,
            )
            identity = tuple(item.casefold() for item in constraint)
            if constraint and identity not in seen_unique_constraints:
                unique_constraints.append(constraint)
                seen_unique_constraints.add(identity)
        if unique_constraints:
            table["unique_constraints"] = unique_constraints
        foreign_keys = _foreign_keys(
            table_raw.get("foreign_keys"), allowed=column_lookup, secrets=secrets
        )
        if foreign_keys:
            table["foreign_keys"] = foreign_keys

        rows: list[dict[str, Any]] = []
        for row_raw in _sequence(table_raw.get("rows"))[:MAX_ROWS_PER_TABLE]:
            if not isinstance(row_raw, Mapping):
                continue
            row = {
                column["name"]: _safe_cell(
                    row_raw.get(column["name"]),
                    secrets=secrets,
                    secret_numbers=secret_numbers,
                )
                for column in columns
                if column["name"] in row_raw
            }
            if row:
                rows.append(row)
        table["rows"] = rows
        tables.append(table)

    if not tables:
        return None
    # Cross-check foreign-key targets after every table has been normalized.
    # This prevents generated or malformed metadata from presenting an
    # invented relationship as a declared schema fact.
    table_columns = {
        str(table["name"]).casefold(): (
            str(table["name"]),
            {
                str(column["name"]).casefold(): str(column["name"])
                for column in table["columns"]
            },
        )
        for table in tables
    }
    for table in tables:
        valid_foreign_keys = []
        seen_foreign_keys: set[tuple[Any, ...]] = set()
        for foreign_key in table.get("foreign_keys", []):
            target = table_columns.get(
                str(foreign_key["references_table"]).casefold()
            )
            if target is None:
                continue
            target_table, target_columns = target
            canonical_target_columns = [
                target_columns.get(str(column).casefold())
                for column in foreign_key["references_columns"]
            ]
            if not all(canonical_target_columns):
                continue
            normalized = {
                "columns": list(foreign_key["columns"]),
                "references_table": target_table,
                "references_columns": canonical_target_columns,
            }
            identity = (
                tuple(item.casefold() for item in normalized["columns"]),
                target_table.casefold(),
                tuple(item.casefold() for item in canonical_target_columns),
            )
            if identity not in seen_foreign_keys:
                valid_foreign_keys.append(normalized)
                seen_foreign_keys.add(identity)
        if valid_foreign_keys:
            table["foreign_keys"] = valid_foreign_keys
        else:
            table.pop("foreign_keys", None)
    result = {"tables": tables}
    encoded = json.dumps(result, ensure_ascii=False, separators=(",", ":"))
    if len(encoded.encode("utf-8")) > MAX_OUTPUT_BYTES:
        return None
    return result


def sanitize_schema_preview(value: Any, *, forbidden_sql: str = "") -> str | None:
    """Serialize a learner-safe schema preview with deterministic formatting."""

    result = sanitize_schema_preview_object(value, forbidden_sql=forbidden_sql)
    if result is None:
        return None
    return json.dumps(result, ensure_ascii=False, separators=(",", ":"))


__all__ = ["sanitize_schema_preview", "sanitize_schema_preview_object"]
